-- ============================================================
-- HABILITAR RLS EM TODAS AS TABELAS — COISAS BRASILEIRAS
-- O app conecta direto no Postgres com o usuario "postgres" (dono das
-- tabelas), que ignora RLS por padrao - entao habilitar aqui nao muda
-- nada pro site/admin. O que isso corrige e a exposicao das tabelas pela
-- API REST/GraphQL automatica do Supabase: sem RLS, qualquer tabela do
-- schema public fica acessivel por ali. Nao criamos nenhuma policy de
-- proposito - isso bloqueia totalmente o acesso anonimo/autenticado via
-- API do Supabase, que este projeto nao usa.
-- ============================================================

ALTER TABLE _MIGRACOES_APLICADAS ENABLE ROW LEVEL SECURITY;
ALTER TABLE TAB_ASSINATURA_CLUBE ENABLE ROW LEVEL SECURITY;
ALTER TABLE TAB_AUDITORIA ENABLE ROW LEVEL SECURITY;
ALTER TABLE TAB_AVALIACAO_PRODUTO ENABLE ROW LEVEL SECURITY;
ALTER TABLE TAB_BANNER ENABLE ROW LEVEL SECURITY;
ALTER TABLE TAB_BLING_NOTA_NOTIFICADA ENABLE ROW LEVEL SECURITY;
ALTER TABLE TAB_BLING_PEDIDO_PENDENTE ENABLE ROW LEVEL SECURITY;
ALTER TABLE TAB_CATEGORIA ENABLE ROW LEVEL SECURITY;
ALTER TABLE TAB_CLIENTE ENABLE ROW LEVEL SECURITY;
ALTER TABLE TAB_COMPRA ENABLE ROW LEVEL SECURITY;
ALTER TABLE TAB_COMPRA_ITEM ENABLE ROW LEVEL SECURITY;
ALTER TABLE TAB_CONFIGURACAO ENABLE ROW LEVEL SECURITY;
ALTER TABLE TAB_CONTA ENABLE ROW LEVEL SECURITY;
ALTER TABLE TAB_COTACAO ENABLE ROW LEVEL SECURITY;
ALTER TABLE TAB_COTACAO_ITEM ENABLE ROW LEVEL SECURITY;
ALTER TABLE TAB_CUPOM ENABLE ROW LEVEL SECURITY;
ALTER TABLE TAB_ENDERECO ENABLE ROW LEVEL SECURITY;
ALTER TABLE TAB_FEEDBACK ENABLE ROW LEVEL SECURITY;
ALTER TABLE TAB_FORNECEDOR ENABLE ROW LEVEL SECURITY;
ALTER TABLE TAB_FRETE_FAIXA ENABLE ROW LEVEL SECURITY;
ALTER TABLE TAB_INTEGRACAO_BLING ENABLE ROW LEVEL SECURITY;
ALTER TABLE TAB_INTEGRACAO_SEGREDO ENABLE ROW LEVEL SECURITY;
ALTER TABLE TAB_LISTA_DESEJOS ENABLE ROW LEVEL SECURITY;
ALTER TABLE TAB_NOTIFICACAO_ESTOQUE ENABLE ROW LEVEL SECURITY;
ALTER TABLE TAB_ORCAMENTO ENABLE ROW LEVEL SECURITY;
ALTER TABLE TAB_ORCAMENTO_ITEM ENABLE ROW LEVEL SECURITY;
ALTER TABLE TAB_PEDIDO ENABLE ROW LEVEL SECURITY;
ALTER TABLE TAB_PEDIDO_COMPRA ENABLE ROW LEVEL SECURITY;
ALTER TABLE TAB_PEDIDO_COMPRA_ITEM ENABLE ROW LEVEL SECURITY;
ALTER TABLE TAB_PEDIDO_ITEM ENABLE ROW LEVEL SECURITY;
ALTER TABLE TAB_PRODUTO ENABLE ROW LEVEL SECURITY;
ALTER TABLE TAB_PRODUTO_CATEGORIA ENABLE ROW LEVEL SECURITY;
ALTER TABLE TAB_PRODUTO_IMAGEM ENABLE ROW LEVEL SECURITY;
ALTER TABLE TAB_SOBRE_NOS_MIDIA ENABLE ROW LEVEL SECURITY;
ALTER TABLE TAB_TIPO_ENTREGA ENABLE ROW LEVEL SECURITY;
ALTER TABLE TAB_USUARIO_ADMIN ENABLE ROW LEVEL SECURITY;

INSERT INTO _migracoes_aplicadas (versao) VALUES ('045')
ON CONFLICT (versao) DO NOTHING;

-- ============================================================
-- FIM DO SCRIPT
-- ============================================================
