-- CreateEnum
CREATE TYPE "StatusPedido" AS ENUM ('AGUARDANDO_PAGAMENTO', 'PAGO', 'EM_SEPARACAO', 'ENVIADO', 'ENTREGUE', 'CANCELADO');

-- CreateEnum
CREATE TYPE "PapelUsuarioAdmin" AS ENUM ('ADMIN', 'OPERADOR');

-- CreateTable
CREATE TABLE "TAB_CATEGORIA" (
    "id" TEXT NOT NULL,
    "nome" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "ativa" BOOLEAN NOT NULL DEFAULT true,
    "criadoEm" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TAB_CATEGORIA_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TAB_PRODUTO" (
    "id" TEXT NOT NULL,
    "nome" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "descricao" TEXT,
    "preco" DECIMAL(10,2) NOT NULL,
    "precoPromocional" DECIMAL(10,2),
    "estoque" INTEGER NOT NULL DEFAULT 0,
    "ativo" BOOLEAN NOT NULL DEFAULT true,
    "criadoEm" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "atualizadoEm" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TAB_PRODUTO_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TAB_PRODUTO_CATEGORIA" (
    "produtoId" TEXT NOT NULL,
    "categoriaId" TEXT NOT NULL,

    CONSTRAINT "TAB_PRODUTO_CATEGORIA_pkey" PRIMARY KEY ("produtoId","categoriaId")
);

-- CreateTable
CREATE TABLE "TAB_PRODUTO_IMAGEM" (
    "id" TEXT NOT NULL,
    "produtoId" TEXT NOT NULL,
    "url" TEXT NOT NULL,
    "ordem" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "TAB_PRODUTO_IMAGEM_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TAB_CLIENTE" (
    "id" TEXT NOT NULL,
    "nome" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "telefone" TEXT,
    "cpfCnpj" TEXT,
    "senhaHash" TEXT NOT NULL,
    "criadoEm" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TAB_CLIENTE_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TAB_ENDERECO" (
    "id" TEXT NOT NULL,
    "clienteId" TEXT NOT NULL,
    "cep" TEXT NOT NULL,
    "logradouro" TEXT NOT NULL,
    "numero" TEXT NOT NULL,
    "complemento" TEXT,
    "bairro" TEXT NOT NULL,
    "cidade" TEXT NOT NULL,
    "estado" TEXT NOT NULL,
    "principal" BOOLEAN NOT NULL DEFAULT false,

    CONSTRAINT "TAB_ENDERECO_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TAB_PEDIDO" (
    "id" TEXT NOT NULL,
    "clienteId" TEXT NOT NULL,
    "enderecoId" TEXT NOT NULL,
    "status" "StatusPedido" NOT NULL DEFAULT 'AGUARDANDO_PAGAMENTO',
    "total" DECIMAL(10,2) NOT NULL,
    "formaPagamento" TEXT,
    "notaFiscalUrl" TEXT,
    "criadoEm" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "atualizadoEm" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TAB_PEDIDO_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TAB_PEDIDO_ITEM" (
    "id" TEXT NOT NULL,
    "pedidoId" TEXT NOT NULL,
    "produtoId" TEXT NOT NULL,
    "quantidade" INTEGER NOT NULL,
    "precoUnitario" DECIMAL(10,2) NOT NULL,

    CONSTRAINT "TAB_PEDIDO_ITEM_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TAB_USUARIO_ADMIN" (
    "id" TEXT NOT NULL,
    "nome" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "senhaHash" TEXT NOT NULL,
    "papel" "PapelUsuarioAdmin" NOT NULL DEFAULT 'OPERADOR',
    "ativo" BOOLEAN NOT NULL DEFAULT true,
    "criadoEm" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TAB_USUARIO_ADMIN_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "TAB_CATEGORIA_slug_key" ON "TAB_CATEGORIA"("slug");

-- CreateIndex
CREATE UNIQUE INDEX "TAB_PRODUTO_slug_key" ON "TAB_PRODUTO"("slug");

-- CreateIndex
CREATE UNIQUE INDEX "TAB_CLIENTE_email_key" ON "TAB_CLIENTE"("email");

-- CreateIndex
CREATE UNIQUE INDEX "TAB_CLIENTE_cpfCnpj_key" ON "TAB_CLIENTE"("cpfCnpj");

-- CreateIndex
CREATE UNIQUE INDEX "TAB_USUARIO_ADMIN_email_key" ON "TAB_USUARIO_ADMIN"("email");

-- AddForeignKey
ALTER TABLE "TAB_PRODUTO_CATEGORIA" ADD CONSTRAINT "TAB_PRODUTO_CATEGORIA_produtoId_fkey" FOREIGN KEY ("produtoId") REFERENCES "TAB_PRODUTO"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TAB_PRODUTO_CATEGORIA" ADD CONSTRAINT "TAB_PRODUTO_CATEGORIA_categoriaId_fkey" FOREIGN KEY ("categoriaId") REFERENCES "TAB_CATEGORIA"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TAB_PRODUTO_IMAGEM" ADD CONSTRAINT "TAB_PRODUTO_IMAGEM_produtoId_fkey" FOREIGN KEY ("produtoId") REFERENCES "TAB_PRODUTO"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TAB_ENDERECO" ADD CONSTRAINT "TAB_ENDERECO_clienteId_fkey" FOREIGN KEY ("clienteId") REFERENCES "TAB_CLIENTE"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TAB_PEDIDO" ADD CONSTRAINT "TAB_PEDIDO_clienteId_fkey" FOREIGN KEY ("clienteId") REFERENCES "TAB_CLIENTE"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TAB_PEDIDO" ADD CONSTRAINT "TAB_PEDIDO_enderecoId_fkey" FOREIGN KEY ("enderecoId") REFERENCES "TAB_ENDERECO"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TAB_PEDIDO_ITEM" ADD CONSTRAINT "TAB_PEDIDO_ITEM_pedidoId_fkey" FOREIGN KEY ("pedidoId") REFERENCES "TAB_PEDIDO"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TAB_PEDIDO_ITEM" ADD CONSTRAINT "TAB_PEDIDO_ITEM_produtoId_fkey" FOREIGN KEY ("produtoId") REFERENCES "TAB_PRODUTO"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
